# These are supported funding model platforms

patreon: Arcaniax # Replace with a single Patreon username
custom: https://www.paypal.me/LesleyDom # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']