name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    strategy:
      matrix:
        java: ["1.8", "11"]
        os: ["ubuntu-18.04"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup JDK ${{ matrix.java }}"
        uses: "actions/setup-java@v1.4.3"
        with:
          java-version: "${{ matrix.java }}"
      - name: "Clean Build"
        run: "./gradlew clean build"